services:
  ##############################
  # 🧬 MinIO (Object Storage)
  ##############################
  miniogc:
    image: minio/minio
    container_name: ${COMPOSE_PROJECT_NAME}_miniogc
    ports:
      - "${FORWARD_MINIO_S3_PORT}:9000"   # S3 API (host 9100 -> container 9000)
      - "${FORWARD_MINIO_UI_PORT}:9001"   # Web UI  (host 9101 -> container 9001)
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - miniogc_data:/data
    command: server /data --console-address ":9001"


  miniogc-init:
    image: minio/mc
    container_name: ${COMPOSE_PROJECT_NAME}_miniogc_init
    depends_on:
      - miniogc
    entrypoint: ["/bin/sh", "/init.sh"]
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./infra/minio/init.sh:/init.sh:ro
    restart: "no"
volumes:
  miniogc_data:

